import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfólio Guilherme",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt_BR">
      <head>
        <meta content="width=device-width, initial-scale=0.5" name="viewport" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
