import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/document";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfólio Guilherme",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt_BR">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=.5" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              document.querySelectorAll('meta[name="viewport"]').forEach((meta, index) => {
                if (index > 0) meta.remove();
              });
            `,
          }}
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
